export const EVENT_LUCKY_ABI = [
  {
    type: 'constructor',
    inputs: [{ name: '_usdc', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createEvent',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'minNumber', type: 'uint16' },
      { name: 'maxNumber', type: 'uint16' },
      { name: 'registrationDeadline', type: 'uint256' },
      { name: 'prizeAmounts', type: 'uint256[]' },
      { name: 'maxRegistrations', type: 'uint256' },
    ],
    outputs: [{ name: 'eventId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'register',
    inputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'chosenNumber', type: 'uint16' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'commitDraw',
    inputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'secretHash', type: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'draw',
    inputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'secret', type: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelDraw',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claim',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'reclaimUnclaimed',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getEvent',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [
      { name: 'host', type: 'address' },
      { name: 'name', type: 'string' },
      { name: 'minNumber', type: 'uint16' },
      { name: 'maxNumber', type: 'uint16' },
      { name: 'registrationDeadline', type: 'uint256' },
      {
        name: 'prizes',
        type: 'tuple[]',
        components: [
          { name: 'amount', type: 'uint256' },
          { name: 'rank', type: 'uint8' },
        ],
      },
      { name: 'drawn', type: 'bool' },
      { name: 'winningNumber', type: 'uint16' },
      { name: 'claimDeadline', type: 'uint256' },
      { name: 'exists', type: 'bool' },
      { name: 'totalPrize', type: 'uint256' },
      { name: 'escrowRemaining', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getWinners',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [
      { name: 'winners', type: 'address[]' },
      { name: 'amounts', type: 'uint256[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'winnerAmount',
    inputs: [
      { name: '', type: 'uint256' },
      { name: '', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasRegistered',
    inputs: [
      { name: '', type: 'uint256' },
      { name: '', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextEventId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'EventCreated',
    inputs: [
      { name: 'eventId', type: 'uint256', indexed: true },
      { name: 'host', type: 'address', indexed: true },
      { name: 'name', type: 'string', indexed: false },
      { name: 'totalPrize', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PlayerRegistered',
    inputs: [
      { name: 'eventId', type: 'uint256', indexed: true },
      { name: 'player', type: 'address', indexed: true },
      { name: 'chosenNumber', type: 'uint16', indexed: false },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DrawCompleted',
    inputs: [
      { name: 'eventId', type: 'uint256', indexed: true },
      { name: 'winningNumber', type: 'uint16', indexed: false },
      { name: 'winners', type: 'address[]', indexed: false },
      { name: 'amounts', type: 'uint256[]', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PrizeClaimed',
    inputs: [
      { name: 'eventId', type: 'uint256', indexed: true },
      { name: 'winner', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
] as const
